### PR TITLE
Adding nested capacity to VM

### PR DESCRIPTION
**Pull request by cedlecomte**

### CODE REVIEW

**Comment by dsavineau** [comment]
Why don't you use host-passthrough instead of hardcode the value for core2duo ?

```
<cpu mode='host-passthrough'>
</cpu>
```

**Comment by cedlecomte** [comment]
Like this ?

**Comment by dyasny** [comment]
Typically, in environments where live migration is done, and CPU baseline is (for example) Westmere, you should be using

  <cpu mode='custom' match='exact'>
    <model fallback='allow'>Westmere</model>
    <topology sockets='16' cores='1' threads='1'/>
  </cpu>

Which amounts up to '-cpu Westmere' in cmdline. If you don't care about migration or you know for certain all computes are exactly the same, you can use -host of course

**Comment by cedlecomte** [comment]
For now all vm are start on the same hypervisor, so all compute node should have the same flag. The problem will be present when we will spawn a platform on multi hypervisor. Did you see a simple way to do this ?

**Comment by dyasny** [comment]
Weird, the domxml snip failed. What happens in RHEV/oVirt is orientation towards specific cpu models, which should be the lowest available in a cluster. Example - one host is Nehalem, all other hosts are Sandybridge. If you use Nehalem, VMs will migrate across the entire cluster, but if you use "-host", the VMs started on sandybridge hosts will not be able to jump to the nehalem host.

```
  <cpu mode='custom' match='exact'>
    <model fallback='allow'>Nehalem</model>
    <topology sockets='8' cores='1' threads='1'/>
  </cpu>
```

**Pull request merged**
