### PR TITLE
[WIP] add the qcow2 image support

### PR DESCRIPTION
**Pull request by goneri**
Add the ability to use qcow2 image for any nodes. So far, it was only possible for the
install-server.
Also switch the cloud-init image from raw ISO to qcow2.

### CODE REVIEW

**Comment by cedlecomte** [comment]
That could be nice to have different sample for each different way to bootstrap a sps platform (one with qcow2 and one with PXE). And it could be nice to move theses files into the examples dir. What do you think ?

**Comment by goneri** [comment]
Yes, this is a good idea.

**Comment by goneri** [comment]
Please do not merge for the moment.

**Comment by Prophidys** [comment]
If you don't want a merge, juste close the pull request and submit it later :-)

**Pull request closed without merging**
